### ISSUE TITLE
Need 64-bit support

### ISSUE THREAD

**Issue by droscoe** [JayFoxRox/VPinMAME_SPA#3]
A big push recently has resulted in a large number of people migrating VPin tools to 64-bit, which is no longer compatible with this version.  Any chance of this being updated for 64-bit?

**Comment by JayFoxRox** [comment]
> Any chance of this being updated for 64-bit?

No for multiple reasons.

First of all I'm personally no longer working on this; if a PR lands, I'll review it when I find time.
Note that I created https://github.com/JayFoxRox/stern-pba-emu but the code in this repository is by @djrobx.

However, more importantly, this is only loading the FarSight Studio / Stern DLLs which are 32-bit / x86 code.

---

*(The following is written under the assumption that FarSight Studio / Stern don't ship x64 DLLs; if there are x64 DLLs then x64 support would be trivial)*

You'd need a full Windows API wrapper and x86 emulator to continue running those DLLs if you wanted to run them in a 64-bit context "natively" - but that's potentially a lot of work.
For x64, an alternative would be to create a 32-bit thread / context using 32-bit CS/DS segments, but it's not trivial either and not as future-proof (wouldn't work on ARM for example).

A more trivial way to deal with this is to run the DLLs in a 32-bit process and communicate to it via network or shared-memory. It's a poor approach, but it's at least somewhat future-proof (qemu-user / full Windows VM for accessing the x86 DLL).

The proper solution is to just write a proper Spike system emulator (HLE or full system), which I had prototyped privately: https://www.patreon.com/posts/update-february-17686171
That way you run the actual code that runs on the real pinball machine.
It will be compatible with more games and it's more future-proof (access to all game versions, works on ARM/x86/x64/any, supports all game features such as secondary displays, etc.).

---

I'm going to close this issue, because I consider 64-bit to not be feasible in the current codebase / ecosystem; the proposed solutions would deserve their own projects.

Closed.

**Comment by djrobx** [comment]
All of the above is correct.  At the time this project was created, TPA/SPA were 32 bit only, so there is no 64 bit DLL for this project to interface with.   Even if there were, this project is not compatible with the DLLs provided with newer TPA/SPA builds.    There is no benefit to running the existing tables in 64 bit mode, you can continue to just use a 32 bit VPX ecosystem for this purpose.
